joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 100

seed_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - THK_PCS9S330
#    - torso_joint
#    - shoulder_joint
#    - elbow_joint
#    - eef_joint
